CREATE DATABASE CON_CUNG

--A. PHAN TICH PROFIT
--1.LN THEO TIME
;
WITH T1 AS (
SELECT YEAR(ORDER_DATE) AS YEAR,
        MONTH(ORDER_DATE) AS MONTH,
        CEILING(MONTH(ORDER_DATE) / 6.0) AS Half_Year,
        SUM(REVENUE) - SUM(COGS) - SUM(DISCOUNT_AMOUNT) AS Total_Profit
    FROM fact_sales
    GROUP BY YEAR(ORDER_DATE), MONTH(ORDER_DATE)
    )
, T2 AS (
    SELECT YEAR, [MONTH], Half_Year, Total_Profit,
            Total_Profit *100 / SUM(Total_Profit) OVER(PARTITION BY [YEAR]) AS PERCENTAGE,
            SUM(Total_Profit) OVER(PARTITION BY [YEAR], Half_Year) AS Total_Profit_By_HalfYear
        FROM T1
    )
    SELECT *,
            CASE WHEN LAG(Total_Profit_By_HalfYear) OVER(ORDER BY [YEAR], [MONTH]) IS NULL THEN 0
            ELSE (Total_Profit_By_HalfYear - LAG(Total_Profit_By_HalfYear) OVER(ORDER BY [YEAR],[MONTH])) *100 / LAG(Total_Profit_By_HalfYear) OVER(ORDER BY [YEAR],[MONTH])
            END AS YoY_HalfMonth
        FROM T2
        ORDER BY [YEAR], [MONTH]


--2.PROFIT THEO KHU VUC & KENH BAN HANG
WITH T1 AS (
SELECT YEAR(ORDER_DATE) AS YEAR, CEILING(MONTH(ORDER_DATE) / 6.0) AS Half_Year, CHANNEL,
        SUM(REVENUE) - SUM(COGS) - SUM(DISCOUNT_AMOUNT) AS Total_Profit
    FROM fact_sales
    GROUP BY YEAR(ORDER_DATE), CEILING(MONTH(ORDER_DATE) / 6.0), CHANNEL
    )
    SELECT *,
            CAST((Total_Profit *100 / SUM(Total_Profit) OVER(PARTITION BY [YEAR], Half_Year)) AS decimal(10,2)) AS PERCENTAGE,
            RANK() OVER(PARTITION BY [YEAR], Half_Year ORDER BY Total_Profit DESC) AS R
        FROM T1

--> DOANH THU THEO THU BAC WEB -> APP -> STORE

;
WITH T1 AS (
SELECT REGION,
        SUM(REVENUE) - SUM(COGS) - SUM(DISCOUNT_AMOUNT) AS Total_Profit
    FROM fact_sales
    GROUP BY REGION
    )
, T2 AS (
    SELECT *,
            CAST((Total_Profit *100 / SUM(Total_Profit) OVER()) AS decimal(10,2)) AS PERCENTAGE
        FROM T1
    )
    SELECT *,
            SUM([PERCENTAGE]) OVER(ORDER BY PERCENTAGE DESC) AS PARETO
        FROM T2

--> 2 KHU VUC DONG GOP DOANH THU LON: HA NOI VA HCM
;
WITH T1 AS (
SELECT YEAR(ORDER_DATE) AS YEAR, REGION, CHANNEL,
        SUM(REVENUE) - SUM(COGS) - SUM(DISCOUNT_AMOUNT) AS Total_Profit,
        DENSE_RANK() OVER(PARTITION BY YEAR(ORDER_DATE), CHANNEL ORDER BY (SUM(REVENUE) - SUM(DISCOUNT_AMOUNT)) DESC) AS DR
    FROM fact_sales
    GROUP BY YEAR(ORDER_DATE), REGION, CHANNEL
    )
    SELECT *
        FROM T1
        WHERE DR <= 5

--> phan tich hanh vi va tieu dung cua cac thanh pho DONG GOP DOANH THU LON: HCM & HN CHO  VIEC SU DUNG  app, website & store
-- GIAM CHI PHI, NHAM DEN KHACH HANG TIEM NANG
      
--3.HIEU QUA MARKETING
--BANG TONG QUAT
;
WITH T1 AS (
SELECT S.ORDER_ID, S.CUSTOMER_ID, S.PRODUCT_ID, S.CHANNEL, S.CHANNEL_MARKETING, M.CHANNEL AS CHANNEL_FACTMARKETING,S.REGION, S.ORDER_DATE, S.REVENUE, S.COGS, 
        S.DISCOUNT_AMOUNT, S.[STATUS], C.CAMPAIGN_ID ,M.CLICKS, M.IMPRESSION, M.VISIT, M.SPEND, C.CAMPAIGN_NAME, C.OBJECTIVE
    FROM fact_sales S
        INNER JOIN fact_marketing M ON M.CAMPAIGN_ID = CAST(S.CAMPAIGN_ID AS decimal(10)) AND S.CHANNEL_MARKETING = M.CHANNEL
        INNER JOIN dim_campaign C ON C.CAMPAIGN_ID = CAST(S.CAMPAIGN_ID AS decimal(10))
    )
    SELECT ORDER_ID, CUSTOMER_ID, PRODUCT_ID, CHANNEL_FACTMARKETING ,REGION, ORDER_DATE, REVENUE, COGS, 
        DISCOUNT_AMOUNT, [STATUS] , CAMPAIGN_ID, CLICKS, IMPRESSION, VISIT, SPEND, CAMPAIGN_NAME, OBJECTIVE
        FROM T1
        ORDER BY CAMPAIGN_ID


--PHAN TICH KENH MARKETING TOAN CHIEN DICH
;
WITH CTE_OVERALL AS (
SELECT S.ORDER_ID, S.CUSTOMER_ID, S.PRODUCT_ID, S.CHANNEL, S.CHANNEL_MARKETING, M.CHANNEL AS CHANNEL_FACTMARKETING,S.REGION, S.ORDER_DATE, S.REVENUE, S.COGS, 
        S.DISCOUNT_AMOUNT, S.[STATUS], C.CAMPAIGN_ID ,M.CLICKS, M.IMPRESSION, M.VISIT, M.SPEND, C.CAMPAIGN_NAME, C.OBJECTIVE,
        CASE 
            WHEN S.CHANNEL NOT IN ('APP','WEB') THEN 'STORE'
            ELSE S.CHANNEL_MARKETING
        END AS SEGMENT
    FROM fact_sales S
        INNER JOIN fact_marketing M ON M.CAMPAIGN_ID = CAST(S.CAMPAIGN_ID AS decimal(10)) AND S.CHANNEL_MARKETING = M.CHANNEL
        INNER JOIN dim_campaign C ON C.CAMPAIGN_ID = CAST(S.CAMPAIGN_ID AS decimal(10))
    )
, CTE_REVENUE_PROFIT AS (
    SELECT CHANNEL_MARKETING,
            COUNT(DISTINCT ORDER_ID) AS Total_Order, 
            SUM(REVENUE) AS Total_REVENUE,
            SUM(REVENUE) - SUM(COGS) - SUM(DISCOUNT_AMOUNT) AS Total_Profit
        FROM CTE_OVERALL
        GROUP BY CHANNEL_MARKETING
    )
, CTE_INDEX_MARKETING AS (
    SELECT CHANNEL, SUM(SPEND) AS SPEND, sum(CLICKS) AS CLICKS,
            CAST((SUM(CLICKS) *100 / SUM(IMPRESSION)) AS decimal(10,2)) AS CTR,
            CAST((SUM(SPEND) / SUM(CLICKS)) AS decimal(10)) AS CPC,
            CAST(((SUM(SPEND) / SUM(IMPRESSION)) * 1000) AS DECIMAL(10)) AS CPM
        FROM fact_marketing 
        GROUP BY CHANNEL   
    )
    SELECT M.CHANNEL, 
            CASE 
                WHEN M.CHANNEL IN ('Google','Shopee','Lazada') THEN 'SEARCH/E-commerce'
                WHEN M.CHANNEL IN ('Facebook','TikTok','Instagram','Zalo','YouTube') THEN 'Social_Media'
                ELSE 'OWNER/DIRECT'
            END AS SEGMENT2,
            SPEND, Total_REVENUE, Total_Profit, CTR, CPC, CPM,
            CAST((Total_Order * 100 / CLICKS) AS decimal(10,2)) AS CR,
            CAST((Total_REVENUE *100 / SPEND) AS decimal(10,2)) AS ROAS,
            CAST((Total_Profit *100 / SPEND) AS DECIMAL(10,2)) AS ROI
        FROM CTE_INDEX_MARKETING M
            INNER JOIN CTE_REVENUE_PROFIT RP ON RP.CHANNEL_MARKETING = M.CHANNEL


--PHAN TICH KENH MARKETING THEO MOI CHIEN DICH 

WITH CTE_OVERALL AS (
SELECT S.ORDER_ID, S.CUSTOMER_ID, S.PRODUCT_ID, S.CHANNEL, S.CHANNEL_MARKETING, M.CHANNEL AS CHANNEL_FACTMARKETING,S.REGION, S.ORDER_DATE, S.REVENUE, S.COGS, 
        S.DISCOUNT_AMOUNT, S.[STATUS], C.CAMPAIGN_ID ,M.CLICKS, M.IMPRESSION, M.VISIT, M.SPEND, C.CAMPAIGN_NAME, C.OBJECTIVE,
        CASE 
            WHEN MONTH(C.START_DATE) IN (1,2) THEN 'Tet_Holidays'
            WHEN MONTH(C.START_DATE) IN (3,4,5) THEN 'Low_Season'
            WHEN MONTH(C.START_DATE) IN (6,7) THEN 'Summer_Sale'
            WHEN MONTH(C.START_DATE) IN (8,9) THEN 'Back_to_School'
            WHEN MONTH(C.START_DATE) IN (10,11,12) THEN 'YearEnd_Sale'        
        END AS SEASON
    FROM fact_sales S
        INNER JOIN fact_marketing M ON M.CAMPAIGN_ID = CAST(S.CAMPAIGN_ID AS decimal(10)) AND S.CHANNEL_MARKETING = M.CHANNEL
        INNER JOIN dim_campaign C ON C.CAMPAIGN_ID = CAST(S.CAMPAIGN_ID AS decimal(10))
    )
, CTE_REVENUE_PROFIT AS (
    SELECT SEASON, CAMPAIGN_ID, CAMPAIGN_NAME, OBJECTIVE, CHANNEL_FACTMARKETING,
            COUNT(DISTINCT ORDER_ID) AS Total_Order,
            SUM(REVENUE) AS Total_REVENUE,
            SUM(REVENUE) - SUM(COGS) - SUM(DISCOUNT_AMOUNT) AS Total_Profit
        FROM CTE_OVERALL
        GROUP BY SEASON, CAMPAIGN_ID, CAMPAIGN_NAME, OBJECTIVE, CHANNEL_FACTMARKETING
    )
, CTE_INDEX AS (
    SELECT SEASON, m.CAMPAIGN_ID, CAMPAIGN_NAME, CHANNEL_FACTMARKETING, Total_Order, Total_REVENUE, Total_Profit,
            IMPRESSION, VISIT, CLICKS, SPEND,
            CAST((CLICKS *100 / IMPRESSION) AS decimal(10,2)) AS CTR,
            CAST((SPEND / CLICKS) AS decimal(10)) AS CPC,
            CAST(((SPEND / IMPRESSION) * 1000) AS DECIMAL(10)) AS CPM,
            CAST((Total_Order * 100 / CLICKS) AS decimal(10,2)) AS CR,
            CAST((Total_REVENUE *100 / SPEND) AS decimal(10,2)) AS ROAS,
            CAST((Total_Profit *100 / SPEND) AS DECIMAL(10,2)) AS ROI
        FROM CTE_REVENUE_PROFIT RF
            INNER JOIN fact_marketing M ON M.CAMPAIGN_ID = RF.CAMPAIGN_ID AND M.CHANNEL = RF.CHANNEL_FACTMARKETING
    )
, CTE_Score_Lowseason AS (
    SELECT *,
            (CTR - MIN_CTR) *100 / (MAX_CTR - MIN_CTR) AS Score_CTR,
            (MAX_CPM - CPM) *100 / (MAX_CPM - MIN_CPM) AS Score_CPM,
            (ROI - MIN_ROI) *100 / (MAX_ROI - MIN_ROI) AS Score_ROI
        FROM(
        SELECT *,
                MIN(CTR) OVER(PARTITION BY SEASON) AS MIN_CTR,
                MAX(CTR) OVER(PARTITION BY SEASON) AS MAX_CTR,
                MIN(CPM) OVER(PARTITION BY SEASON) AS MIN_CPM,
                MAX(CPM) OVER(PARTITION BY SEASON) AS MAX_CPM,
                MIN(ROI) OVER(PARTITION BY SEASON) AS MIN_ROI,
                MAX(ROI) OVER(PARTITION BY SEASON) AS MAX_ROI
            FROM CTE_INDEX
        ) AS T
    )
    SELECT SEASON, CAMPAIGN_ID, CAMPAIGN_NAME, CHANNEL_FACTMARKETING, CTR, CPC, CPM, CR, ROAS, ROI,
            Score_CTR * 0.5 + Score_CPM * 0.3 + Score_ROI * 0.2 AS Score_SEASON,
            DENSE_RANK() OVER(PARTITION BY SEASON 
                ORDER BY
                    CASE
                        WHEN SEASON IN ('Tet_Holidays','YearEnd_Sale') THEN ROI
                        WHEN SEASON IN ('Tet_Holidays','YearEnd_Sale') THEN ROAS
                        ELSE NULL
                    END DESC,
                    CASE
                        WHEN SEASON IN ('Back_to_School','Summer_Sale') THEN ROI
                        WHEN SEASON IN ('Back_to_School','Summer_Sale') THEN CR 
                        ELSE NULL
                    END DESC,
                    CASE
                        WHEN SEASON IN ('Low_Season') THEN Score_CTR * 0.5 + Score_CPM * 0.3 + Score_ROI * 0.2
                    END DESC
            ) AS DS_4MUA
        FROM CTE_Score_Lowseason 


-- PHAN TICH MARKETING THEO HANH VI KHACH HÀNG (RETENTION RATE)
;
WITH CTE_OVERALL AS (
SELECT S.ORDER_ID, S.CUSTOMER_ID, S.PRODUCT_ID, S.CHANNEL, S.CHANNEL_MARKETING, M.CHANNEL AS CHANNEL_FACTMARKETING,S.REGION, S.ORDER_DATE, S.REVENUE, S.COGS, 
        S.DISCOUNT_AMOUNT, S.[STATUS], C.CAMPAIGN_ID ,M.CLICKS, M.IMPRESSION, M.VISIT, M.SPEND, C.CAMPAIGN_NAME, C.OBJECTIVE
    FROM fact_sales S
        INNER JOIN fact_marketing M ON M.CAMPAIGN_ID = CAST(S.CAMPAIGN_ID AS decimal(10)) AND S.CHANNEL_MARKETING = M.CHANNEL
        INNER JOIN dim_campaign C ON C.CAMPAIGN_ID = CAST(S.CAMPAIGN_ID AS decimal(10))
    )
, CTE_FIRSTORDERDATE AS (
    SELECT CUSTOMER_ID,
            MIN(ORDER_DATE) AS FIRST_ORDERDATE
        FROM CTE_OVERALL
        GROUP BY CUSTOMER_ID
    )
, CTE_FIRSTCAMPAIGN AS (
    SELECT O.CUSTOMER_ID, F.FIRST_ORDERDATE, O.CAMPAIGN_ID
        FROM CTE_FIRSTORDERDATE F
            INNER JOIN CTE_OVERALL O
                ON F.CUSTOMER_ID = O.CUSTOMER_ID
                AND F.FIRST_ORDERDATE = O.ORDER_DATE
    )
, CTE_COHORT AS (
    SELECT O.CUSTOMER_ID, O.ORDER_DATE, F.FIRST_ORDERDATE, FC.CAMPAIGN_ID,
            YEAR(F.FIRST_ORDERDATE) * 100 + MONTH(F.FIRST_ORDERDATE) AS FIRST_ORDERDATE_YEARMONTH,
            DATEDIFF(MONTH,F.FIRST_ORDERDATE,O.ORDER_DATE) AS COHORT
        FROM CTE_OVERALL O
            INNER JOIN CTE_FIRSTORDERDATE F ON O.CUSTOMER_ID = F.CUSTOMER_ID
            INNER JOIN CTE_FIRSTCAMPAIGN FC ON FC.CUSTOMER_ID = O.CUSTOMER_ID
    )
, CTE_NEWCUSTOMERS AS (
    SELECT FIRST_ORDERDATE_YEARMONTH, CAMPAIGN_ID,
            COUNT(DISTINCT CUSTOMER_ID) AS NEW_CUSTOMERS
        FROM CTE_COHORT
        GROUP BY FIRST_ORDERDATE_YEARMONTH, CAMPAIGN_ID
    )
    SELECT C.FIRST_ORDERDATE_YEARMONTH, C.CAMPAIGN_ID,C.COHORT,N.NEW_CUSTOMERS,
            CAST((COUNT(DISTINCT CUSTOMER_ID) *100 / N.NEW_CUSTOMERS) AS decimal(10,2)) AS RETENTION_RATE
        FROM CTE_COHORT C
            INNER JOIN CTE_NEWCUSTOMERS N 
                ON C.FIRST_ORDERDATE_YEARMONTH = N.FIRST_ORDERDATE_YEARMONTH
                AND C.CAMPAIGN_ID = N.CAMPAIGN_ID
        GROUP BY C.FIRST_ORDERDATE_YEARMONTH, C.CAMPAIGN_ID,C.COHORT, N.NEW_CUSTOMERS
        ORDER BY FIRST_ORDERDATE_YEARMONTH, CAMPAIGN_ID, COHORT


SELECT *
    FROM dim_campaign   
    ORDER BY START_DATE
SELECT *
    FROM fact_marketing

EXEC SP_HELP 'fact_sales'





